#!/usr/bin/env python3
"""
Setup Wizard for Kimi K2.5 Agent System
Guides through initial configuration
"""
import os
import sys
import json
import getpass
from pathlib import Path
from datetime import datetime


def print_banner():
    """Print setup banner."""
    print("""
╔════════════════════════════════════════════════════════════╗
║   Kimi K2.5 Multi-Agent Outreach System - Setup Wizard    ║
║   Target: $15K-$30K Revenue in 90 Days                   ║
╚════════════════════════════════════════════════════════════╝
""")


def step_api_keys():
    """Step 1: Configure API keys."""
    print("\n📋 STEP 1: API Configuration")
    print("-" * 50)
    print("\n🔑 REQUIRED: Kimi K2.5 API Key (Moonshot AI)")
    print("   Get yours at: https://platform.moonshot.ai")
    
    moonshot_key = getpass.getpass("   Enter Kimi API Key: ").strip()
    
    if not moonshot_key:
        print("   ⚠️  Warning: No API key provided. System won't work without it.")
    else:
        print("   ✅ API key captured")
    
    print("\n🔗 OPTIONAL: Phantombuster (LinkedIn Automation)")
    print("   Get yours at: https://phantombuster.com")
    pb_key = getpass.getpass("   Enter Phantombuster API Key (optional): ").strip()
    
    print("\n📊 OPTIONAL: Airtable (CRM)")
    print("   Get yours at: https://airtable.com/create")
    at_key = getpass.getpass("   Enter Airtable API Key (optional): ").strip()
    
    return {
        "moonshot_api_key": moonshot_key,
        "phantombuster_api_key": pb_key,
        "airtable_api_key": at_key
    }


def step_user_profile():
    """Step 2: Configure user profile."""
    print("\n\n📋 STEP 2: User Profile")
    print("-" * 50)
    
    name = input("\n👤 Your Name: ").strip()
    title = input("🎯 Your Professional Title: ").strip() or "AI Engineer | Analytics for SaaS"
    linkedin = input("🔗 Your LinkedIn URL: ").strip()
    
    return {
        "user_name": name,
        "user_title": title,
        "linkedin_profile_url": linkedin
    }


def step_niche_allocation():
    """Step 3: Configure niche allocation."""
    print("\n\n📋 STEP 3: Niche Allocation")
    print("-" * 50)
    print("\n🎯 How should we split your outreach efforts?")
    print("   (Default: 70% SaaS Analytics / 30% Agency Automation)")
    
    try:
        saas_pct = input("\n   SaaS Analytics percentage (default 70): ").strip()
        saas_pct = int(saas_pct) if saas_pct else 70
    except:
        saas_pct = 70
    
    agency_pct = 100 - saas_pct
    
    print(f"\n   ✅ Configuration: {saas_pct}% SaaS / {agency_pct}% Agency")
    
    return {
        "niche_allocation": {
            "saas": saas_pct / 100,
            "agency": agency_pct / 100
        }
    }


def step_safety_limits():
    """Step 4: Configure safety limits."""
    print("\n\n📋 STEP 4: Safety Limits (LinkedIn)")
    print("-" * 50)
    print("\n⚠️  To avoid LinkedIn restrictions, we enforce daily limits.")
    print("   Recommended: 20 connections/day, 100/week max")
    
    try:
        daily = input("\n   Daily connection limit (default 20): ").strip()
        daily = int(daily) if daily else 20
    except:
        daily = 20
    
    if daily > 25:
        print(f"   ⚠️  Warning: {daily}/day is risky. Consider 20 or less.")
    
    return {
        "daily_limits": {
            "connections": daily,
            "messages": daily
        },
        "safety": {
            "weekly_connection_limit": daily * 5,
            "min_delay_seconds": 300,
            "max_delay_seconds": 900
        }
    }


def save_config(config: dict):
    """Save configuration to settings.json."""
    config_path = Path("config/settings.json")
    
    # Load existing defaults
    if config_path.exists():
        with open(config_path, 'r') as f:
            existing = json.load(f)
    else:
        existing = {}
    
    # Merge with new config
    existing.update(config)
    existing["setup_date"] = datetime.now().isoformat()
    
    # Save
    with open(config_path, 'w') as f:
        json.dump(existing, f, indent=2)
    
    print(f"\n   ✅ Configuration saved to {config_path}")


def create_env_file(config: dict):
    """Create .env file from config."""
    env_path = Path(".env")
    
    env_content = f"""# Kimi K2.5 Agent System - Environment Variables
# Generated by setup wizard on {datetime.now().strftime('%Y-%m-%d %H:%M')}

# API Keys
MOONSHOT_API_KEY={config.get('moonshot_api_key', '')}
PHANTOMBUSTER_API_KEY={config.get('phantombuster_api_key', '')}
AIRTABLE_API_KEY={config.get('airtable_api_key', '')}

# User Profile
USER_NAME={config.get('user_name', '')}
USER_TITLE={config.get('user_title', 'AI Engineer | Analytics for SaaS')}
LINKEDIN_PROFILE_URL={config.get('linkedin_profile_url', '')}
"""
    
    with open(env_path, 'w') as f:
        f.write(env_content)
    
    print(f"   ✅ Environment file created at {env_path}")


def print_next_steps():
    """Print next steps."""
    print("""
\n╔════════════════════════════════════════════════════════════╗
║   ✅ SETUP COMPLETE!                                         ║
╚════════════════════════════════════════════════════════════╝

🚀 NEXT STEPS:

1. Review your configuration:
   cat config/settings.json

2. Test the system:
   python3 test_system.py

3. Run your first workflow:
   python3 main.py morning      # Research + message generation
   python3 main.py midday       # Send scheduled outreach
   python3 main.py evening      # Wrap-up + metrics

   Or run all at once:
   python3 main.py daily

4. Start automated scheduling (runs daily at 8am, 12pm, 6pm):
   python3 scheduler.py

5. View dashboard:
   python3 main.py dashboard

📚 RESOURCES:

• Full documentation: README.md
• System spec: Kimi-K2.5-Agent-Spec.md
• Templates: /Users/cave/Downloads/linkedin_outreach_*.json
• Offer ladders: /Users/cave/Downloads/*_offer_ladder.json

⚠️  IMPORTANT:

Before sending real outreach:
1. Get Kimi K2.5 API key from https://platform.moonshot.ai
2. Review first 20 generated messages for quality
3. Start with 5-10 test connections to warm up LinkedIn
4. Monitor acceptance rates (target >40%)

🎯 TARGETS (90 days):
• 1,000 LinkedIn connections
• 36 discovery calls  
• 8-11 deals closed
• $21,600 - $57,600 revenue

Good luck! 🚀
""")


def main():
    """Main setup wizard flow."""
    print_banner()
    
    print("\nThis wizard will help you configure the Kimi K2.5 Agent System.")
    print("Press Ctrl+C at any time to cancel.\n")
    
    try:
        # Run all steps
        config = {}
        config.update(step_api_keys())
        config.update(step_user_profile())
        config.update(step_niche_allocation())
        config.update(step_safety_limits())
        
        # Save configuration
        print("\n\n💾 Saving configuration...")
        save_config(config)
        create_env_file(config)
        
        # Print next steps
        print_next_steps()
        
    except KeyboardInterrupt:
        print("\n\n❌ Setup cancelled. Run again anytime with: python3 setup.py")
        sys.exit(1)
    except Exception as e:
        print(f"\n\n❌ Error during setup: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
